package au.com.addstar.serversigns.meta;

public enum SVSMetaKey {
    ADD, CANCEL, CONFIRMATION, COOLDOWN_RESET, COPY, CREATE, EDIT, INSERT, LIST, GRANT, PRICE_ITEM, PRICE_ITEM_CRITERIA, REMOVE, SET_COOLDOWN, SET_GLOBAL_COOLDOWN, PERMISSION, PRICE, XP, YES, LOOP, HOLDING, HELD_ITEM_CRITERIA, LONG, USES, CANCEL_PERMISSION, SILENT, SELECT, OPTION, TIME_LIMIT, IMPORT;

    SVSMetaKey() {
    }
}


